spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        #hbm2ddl.auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  #sql:
    #init:
      #data-locations: classpath:data.sql

  redis:
    host: localhost
    port: 6379
    #password:
  session:
    store-type: redis
    #redis:
      #namespace: test:session

server:
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
        domain: localhost
        http-only: true
      timeout: 3600