spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        #hbm2ddl.auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/test
      username: sa
      password:
  sql:
    init:
      data-locations: classpath:data.sql

  redis:
    host: localhost
    port: 6379
    #password:
  session:
    store-type: redis
    #redis:
      #namespace: test:session

server:
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
        domain: localhost
        http-only: true
      timeout: 3600